# Generated by Django 5.0.4 on 2024-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_stock_alter_product_stock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(),
        ),
    ]
