# Generated by Django 5.0.3 on 2024-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[(0, 'Open'), (1, 'Full'), (2, 'Completed'), (3, 'Discontinued')], default='Open', max_length=20),
        ),
    ]
