# Generated by Django 5.0.3 on 2024-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='Open', max_length=20),
        ),
    ]
