# Generated by Django 5.0.3 on 2024-05-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_commission_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
    ]
