# Generated by Django 5.0.3 on 2024-05-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_alter_jobapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', 'created_on']},
        ),
    ]
