# Generated by Django 5.0.3 on 2024-05-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_commission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
    ]
